title: Learning theoretical linguistics
email: grammarsmith@pm.me
description: A beginner's journey through theoretical linguistics
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://gramrsmith.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: gramrsmith

# Build settings
theme: minima
remote_theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

exclude:
  - CLAUDE.md
  - vendor/
  - .bundle/
